version: "3.4"

services:
  php:
    image: ${CONTAINER_REGISTRY_BASE}/php:${CONTAINER_REGISTRY_TAG}
    build:
      context: .
      target: api_platform_php
    depends_on:
      - mysql
    restart: unless-stopped
    volumes:
      - php_socket:/var/run/php
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s

  caddy:
    image: ${CONTAINER_REGISTRY_BASE}/caddy:${CONTAINER_REGISTRY_TAG}
    build:
      context: .
      target: api_platform_caddy
    depends_on:
      - php
    environment:
      SERVER_NAME: ${SERVER_NAME:-localhost, caddy:80}
      MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET:-!ChangeMe!}
      MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET:-!ChangeMe!}
    restart: unless-stopped
    volumes:
      - php_socket:/var/run/php
      - caddy_data:/data
      - caddy_config:/config
    ports:
      # HTTP
      - target: 80
        published: 80
        protocol: tcp
      # HTTPS
      - target: 443
        published: 443
        protocol: tcp
      # HTTP/3
      - target: 443
        published: 443
        protocol: udp

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: base
      MYSQL_ROOT_PASSWORD: webant
    volumes:
      - ./docker/db/data:/var/lib/mysql:rw
    ports:
      - "3307:3306"

volumes:
  php_socket:
  db_data:
  caddy_data:
  caddy_config:
