apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "api-platform.fullname" . }}
  labels:
    {{- include "api-platform.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "api-platform.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
          {{- include "api-platform.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "api-platform.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-caddy
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.caddy.image.repository }}:{{ .Values.caddy.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.caddy.image.imagePullPolicy }}
          env:
            - name: SERVER_NAME
              value: :80
            - name: MERCURE_PUBLISHER_JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "api-platform.fullname" . }}
                  key: mercure-jwt-secret
            - name: MERCURE_SUBSCRIBER_JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "api-platform.fullname" . }}
                  key: mercure-jwt-secret
          ports:
            - name: http
              containerPort: 80
              protocol: TCP

          volumeMounts:
            - mountPath: /var/run/php
              name: php-socket
          lifecycle:
            preStop:
              exec:
                command: ["curl", "-XPOST", "http://localhost:2019/stop"]
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 3
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
#               limits:
#                 cpu: 256m
#                 memory: 256Mi
#               requests:
#                 cpu: 200m
#                 memory: 200Mi
        - name: {{ .Chart.Name }}-php
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.php.image.repository }}:{{ .Values.php.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.php.image.imagePullPolicy }}
          env:


            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "api-platform.fullname" . }}
                  key: DATABASE_URL
            - name: TRUSTED_PROXIES
              valueFrom:
                configMapKeyRef:
                  name: {{ include "api-platform.fullname" . }}
                  key: TRUSTED_PROXIES
            - name: TRUSTED_HOSTS
              valueFrom:
                configMapKeyRef:
                  name: {{ include "api-platform.fullname" . }}
                  key: TRUSTED_HOSTS
            - name: MERCURE_SUBSCRIBE_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "api-platform.fullname" . }}
                  key: MERCURE_SUBSCRIBE_URL
            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: {{ include "api-platform.fullname" . }}
                  key: APP_ENV
            - name: APP_SECRET
              valueFrom:
                configMapKeyRef:
                  name: {{ include "api-platform.fullname" . }}
                  key: APP_SECRET
            - name: CORS_ALLOW_ORIGIN
              valueFrom:
                configMapKeyRef:
                  name: {{ include "api-platform.fullname" . }}
                  key: CORS_ALLOW_ORIGIN
            - name: MERCURE_PUBLISH_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "api-platform.fullname" . }}
                  key: MERCURE_PUBLISH_URL
            - name: MERCURE_JWT_TOKEN
              valueFrom:
                configMapKeyRef:
                  name: {{ include "api-platform.fullname" . }}
                  key: MERCURE_JWT_TOKEN
            - name: MAILER_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "api-platform.fullname" . }}
                  key: MAILER_URL
            - name: VK_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: {{ include "api-platform.fullname" . }}
                  key: VK_CLIENT_ID
            - name: VK_CLIENT_SECRET
              valueFrom:
                configMapKeyRef:
                  name: {{ include "api-platform.fullname" . }}
                  key: VK_CLIENT_SECRET
            - name: VK_REDIRECT_URI
              valueFrom:
                configMapKeyRef:
                  name: {{ include "api-platform.fullname" . }}
                  key: VK_REDIRECT_URI
            - name: FB_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: {{ include "api-platform.fullname" . }}
                  key: FB_CLIENT_ID
            - name: FB_CLIENT_SECRET
              valueFrom:
                configMapKeyRef:
                  name: {{ include "api-platform.fullname" . }}
                  key: FB_CLIENT_SECRET
            - name: FB_REDIRECT_URI
              valueFrom:
                configMapKeyRef:
                  name: {{ include "api-platform.fullname" . }}
                  key: FB_REDIRECT_URI
            - name: APPLE_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: {{ include "api-platform.fullname" . }}
                  key: APPLE_CLIENT_ID
            - name: APPLE_TEAM_ID
              valueFrom:
                configMapKeyRef:
                  name: {{ include "api-platform.fullname" . }}
                  key: APPLE_TEAM_ID
            - name: APPLE_KEY_FILE_ID
              valueFrom:
                configMapKeyRef:
                  name: {{ include "api-platform.fullname" . }}
                  key: APPLE_KEY_FILE_ID
            - name: APPLE_KEY_FILE_PATH
              valueFrom:
                configMapKeyRef:
                  name: {{ include "api-platform.fullname" . }}
                  key: APPLE_KEY_FILE_PATH
            - name: APPLE_REDIRECT_URI
              valueFrom:
                configMapKeyRef:
                  name: {{ include "api-platform.fullname" . }}
                  key: APPLE_REDIRECT_URI
            - name: LOCK_DSN
              valueFrom:
                configMapKeyRef:
                  name: {{ include "api-platform.fullname" . }}
                  key: LOCK_DSN
            - name: SMS_IS_TEST
              valueFrom:
                configMapKeyRef:
                  name: {{ include "api-platform.fullname" . }}
                  key: SMS_IS_TEST
            - name: OAUTH_PRIVATE_KEY
              valueFrom:
                configMapKeyRef:
                  name: {{ include "api-platform.fullname" . }}
                  key: OAUTH_PRIVATE_KEY
            - name: OAUTH_PRIVATE_KEY_PASS
              valueFrom:
                configMapKeyRef:
                  name: {{ include "api-platform.fullname" . }}
                  key: OAUTH_PRIVATE_KEY_PASS
            - name: OAUTH_ENCRYPTION_KEY
              valueFrom:
                configMapKeyRef:
                  name: {{ include "api-platform.fullname" . }}
                  key: OAUTH_ENCRYPTION_KEY
            - name: OAUTH_PUBLIC_KEY
              valueFrom:
                configMapKeyRef:
                  name: {{ include "api-platform.fullname" . }}
                  key: OAUTH_PUBLIC_KEY


          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "/bin/sleep 1; kill -QUIT 1"]
          readinessProbe:
            exec:
              command:
                - docker-healthcheck
            initialDelaySeconds: 120
            periodSeconds: 3
          livenessProbe:
            exec:
              command:
                - docker-healthcheck
            initialDelaySeconds: 120
            periodSeconds: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
#               limits:
#                 cpu: 256m
#                 memory: 256Mi
#               requests:
#                 cpu: 200m
#                 memory: 200Mi
      volumes:
      - name: php-socket
        emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}